name: Test Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2']

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Dependencies
        run: composer install

      - name: Run Tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist

      - name: Install php-coveralls
        run: composer require php-coveralls/php-coveralls

      - name: Upload Coverage to Coveralls
        run: vendor/bin/php-coveralls -v
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}